### ISSUE TITLE
Don't inherit default font-lock faces.

### ISSUE THREAD

**Issue by jcs090218** [felipeochoa/rjsx-mode#127]
I find out these inherit faces.

* `rjsx-tag` -> `font-lock-function-name-face`
* `rjsx-attr` -> `font-lock-variable-name-face`
* `rjsx-text` -> `font-lock-string-face`

Maybe not to inherit and just specify a color for it?

**Comment by felipeochoa** [comment]
I agree the first 2 inheritances are a bit iffy, but we do need to inherit from something. Otherwise whatever color we select is going to look awful in different themes. I picked the font-lock faces because they are likely to be properly set in themes.

If there are better faces to inherit from, I'll happily merge a PR!
