### ISSUE TITLE
Support for Key Combo

### ISSUE THREAD

**Issue by domtronn** [felipeochoa/rjsx-mode#22]
Hi there, thank you very much for this package! It's by far the most comprehensive JSX mode..

However, I use [Key Combo](https://github.com/uk-ar/key-combo) and when entering an `=` character it replaces it by ` = ` which I don't wanna do inside JSX tags, _i.e._

```js
var x=
// becomes
var x = 
```

I used to use `web-mode` and with that, I added some advice to the `key-combo-pre-command-function` which would ignore this combo inside JSX, with 

```el
(advice-add
   'key-combo-pre-command-function
   :around '(lambda (orig-f &rest args)
              (unless  (and (or (web-mode-jsx-is-html)
                                (equal web-mode-content-type "html"))
                            (member (this-command-keys) '("=" "-" "+")))
                (apply orig-f args))))
```

So you can see the function `(web-mode-jsx-is-html)` would tell me I'm inside a JSX tag.

I was just wondering how I would do this using the JS2 parser and RJSX? Any help would be appreciated! Thanks

**Comment by felipeochoa** [comment]
Thanks for the kind words! You could try something like `(memq (js2-node-type (js2-node-at-point)) (list rjsx-JSX rjsx-JSX-ATTR rjsx-JSX-IDENT rjsx-JSX-MEMBER))`. I'm not sure how `web-mode` works, but it might not work if there's no parse tree (because the file is currently malformed or if it's a very long file and there's a lag in parsing). You could additionally add `=` (no-space) as an expansion to your key combo to have that as a fallback.

**Comment by domtronn** [comment]
That worked a treat, thank you!

Hopefully, file size shouldn't be an issue and even if there is no parse tree, it just sends an error which I'm fine with.
