### ISSUE TITLE
Identation

### ISSUE THREAD

**Issue by k1r496** [felipeochoa/rjsx-mode#27]
Hello, guys!
First of all thank you for making this mode.
Second of all, I have a small issue, and maybe I can get some help.
I am using a react-based javascript framework, and I would like to ask for a small feature.
<img width="267" alt="screen shot 2017-01-14 at 19 53 03" src="https://cloud.githubusercontent.com/assets/11160823/21956912/6911aa5c-da93-11e6-920d-b0131eef5784.png">

In line number 4 the curly bracket is not aligned properly (I think the reason is that I have 2 html tags
separated by comma). But still, can you help me figure out how to fix this? I noticed how the identation is made properly in other modes, but I really like the behaviour of this mode and I am not willing to give up to it because of this small bug.

Thank you!

**Comment by febeling** [comment]
The readme asks indentation bugs to be reported to ja-mode, from which this is inherited.

**Comment by felipeochoa** [comment]
Yup, all indentation issues are in `js-mode`. Since it is built into emacs now, you should follow the directions [here](https://debbugs.gnu.org/Emacs.html). Usually you can get reasonable indentation by wrapping JSX in parentheses. In this case, the indentation is working fine for me after applying the advice described [here](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24896#20).
