### ISSUE TITLE
Custom indent levels for closing tags

### ISSUE THREAD

**Issue by domtronn** [felipeochoa/rjsx-mode#32]
Hi there, the JSX project that I work on has a strict style guide which states that if a tag has _more than one_ attribute then the attributes should each be on a new line, _e.g._

```jsx
<div 
  id="Foo"
  className="foo"
>
  <List className="foo__list">
    { props.items.map(item => <label className="foo__label">{item.text}</label>) }
  </List>
  <Footer
    className="foo__footer"
    text={props.footer}
  />
</div>
```

And in order to de-mark child elements more easily, the style guide _also_ says that the closing angled bracket of a tag should be on a new line and indented inline with the opening tag. *RJSX-Mode* indents the closing tags inline with the props, _e.g._

```jsx
<div 
  id="Foo"
  className="foo"
  >
```

 I know this might not be a usual case, but I was wondering if it is _(or could be)_ possible to configure the indent level of closing tags on new lines?

**Comment by felipeochoa** [comment]
Indentation is handled by js-indent-line, which defers to SGML mode. You'd have to check the configuration options for that. If you find anything, I'd like to create a wiki page on indentation, so let me know!




On Sat, Jan 28, 2017 at 11:59 AM +0000, "Dom Charlesworth" <notifications@github.com> wrote:












Hi there, the JSX project that I work on has a strict style guide which states that if a tag has more than one attribute then the attributes should each be on a new line, e.g.
<div 
  id="Foo"
  className="foo"
>
  <List className="foo__list">
    { props.items.map(item => <label className="foo__label">{item.text}</label>) }
  </List>
  <Footer
    className="foo__footer"
    text={props.footer}
  />
</div>


And in order to de-mark child elements more easily, the style guide also says that the closing angled bracket of a tag should be on a new line and indented inline with the opening tag. RJSX-Mode indents the closing tags inline with the props, e.g.
<div 
  id="Foo"
  className="foo"
  >


I know this might not be a usual case, but I was wondering if it is (or could be) possible to configure the indent level of closing tags on new lines?

**Comment by ibrahima** [comment]
I'd appreciate a solution to this as well, since I think the commonly used Airbnb JSX style guide recommends this style of indentation.

I think an alternative might be to use emacs-prettier, set up the configuration to obey that style, and have it run after save?
