### ISSUE TITLE
Indention bugs are related to unstable dependency

### ISSUE THREAD

**Issue by azer** [felipeochoa/rjsx-mode#38]
Hi Felipe,

Thank you for creating this module, I hope more people will use it and it'll become default in popular distros like spacemacs.

Currently there is a little problem with it; it depends on an unstable version of js2-mode. It's not your fault, probably js2-mode needs to update their package in stable streams. Their latest update on Stable Melpa and GNU packages is version 20170116, but rjsx-mode depends on a newer version, which could be considered as newer version. 

This problem causes indentation issues for people using stable registries.  The `tab` button was not working me until I installed the unstable version of js2-mode. May be you can note this detail in your README to guide new users.

Thanks for the great work,
Azer

**Comment by felipeochoa** [comment]
I'm not sure I understand. `rjsx` does not do anything to the `TAB` keybinding, so I don't think your issue was related to this. If you downgrade to `js2` stable, do you have the same indentation issues in a regular JS buffer? If there's a bug in `js2` mode's indentation code (and it's not due to some other package), then you should report it there so they can upgrade the stable version and fix it.

**Comment by azer** [comment]
@felipeochoa js2-mode stable version doesn't have any problem, rjsx and js2-mode stable combined does have though.

**Comment by felipeochoa** [comment]
What about when using `js2-jsx`?

**Comment by felipeochoa** [comment]
I think #42 addresses this. Feel free to re-open if not
