### ISSUE TITLE
Stable releases should have stable dependencies

### ISSUE THREAD

**Issue by skuro** [felipeochoa/rjsx-mode#42]
The version of `rjsx-mode` deployed on [MELPA stable](https://melpa.org/#/rjsx-mode) depends on `js2-mode 20170504` which is not available yet (currently only [`js2-mode 20170116`](https://stable.melpa.org/#/js2-mode) is available as a stable release). 

As a result of the above combination, I cannot install `rjsx-mode` unless I enable the unstable MELPA repository, which makes the stable release of `rjsx-mode` not that useful.

Is it possible to downgrade the dependency on `js2-mode` to the stable one?

**Comment by felipeochoa** [comment]
Thanks for the report. That is probably the correct immediate fix. The only reason I bumped the version number was the emacs 26 issue, which is not crucial to have in stable. Is that something that would be PR-able, or do I need to do some sort of tagging/branching?

The other option would be to file an issue with `js2` to publish a new release on stable, since they don't support emacs 26 until `20170504`.

**Comment by skuro** [comment]
Not sure whether you mean PR-able as in me contributing a PR or else? If there's no API mismatch with the older `js2-mode` it should be just a matter of pushing a new tag. Something like branch off master + commit fix + push tag should work.

Indeed, I was about to open an issue on `js2-mode` as well but I'm too unfamiliar with their release strategy (I see they release only quite rarely) and I hold my horses at the moment. But would be a good idea nonetheless IMHO.

**Comment by felipeochoa** [comment]
I bumped the version dependency because I need to use a new API they introduced for v26 compatibility. I submitted mooz/js2-mode#435. 

In the meantime I also created a new tag off of the previous release with a higher version number. If MELPA does not pick it up, feel free to open up a PR reverting the previous commit.

**Comment by skuro** [comment]
Thanks. I'll keep an eye on MELPA stable and see when it picks it up. I also upped your ticket on js2-mode :-)

**Comment by skuro** [comment]
MELPA is now up to date and my Emacs is happy with the new versions. Thanks!
