### ISSUE TITLE
How does rjsx-mode play with js2-mode and can it take options

### ISSUE THREAD

**Issue by Martinsos** [felipeochoa/rjsx-mode#44]
Hi @felipeochoa,
thank you for this great library, it works great!
I have one problem: I am not sure if I have to also include and configure js2-mode or js2-jsx-mode? Should I do anything with these two or is having just rjsx-mode enough? Also, how can I specify options to rjsx-mode, like indentation level and similar?

Thanks!

**Comment by felipeochoa** [comment]
`rjsx-mode` is derived from `js2-mode` (and is used instead of `js2-jsx-mode`). Any configurations applied there will apply to `rjsx-mode`. `rjsx-mode` doesn't add any new configuration options, so for indentation in particular you should look to `js2-basic-offset` and `sgml-basic-offset`. `js2` has a multitude of configuration options that you can read about there.
