### ISSUE TITLE
rjsx-delete-creates-full-tag sometimes doesn't work

### ISSUE THREAD

**Issue by blaenk** [felipeochoa/rjsx-mode#48]
I noticed that sometimes pressing `C-d` wouldn't work, it would just delete the next character. I eventually realized that this happened when the tag name hadn't been highlighted yet so at first I added an advice to `(font-lock-ensure)` `:before` the function but that didn't work and I remembered that js2-mode's whole point was about parsing the buffer in order to provide better highlighting, so I changed that call to `(js2-reparse)` and everything seems to be working now!

``` elisp
(define-advice rjsx-delete-creates-full-tag
    (:before (n &optional killflag) js2-reparse)
  "Ensure the document is parsed before attempting to proceed."
  (js2-reparse))
```

I'm no expert in js2-mode's internals though, and perhaps there's a better approach to this than reparsing the entire buffer, but at least for my uses it doesn't seem to be much of an issue so far.

**Comment by felipeochoa** [comment]
You're exactly right in the assessment. During parse, `rjsx` identifies the self-closing slashes that should trigger the `C-d` magic. The reason for not reparsing right before deleting is that in large buffers reparse can take a while. That said there is still room for improving the reliability of `rjsx-delete-creates-full-tag`. `rjsx-electric-lt` and `rjsx-parse-empty-tag` should definitely mark their slashes as self-closing. Are the problematic self-closing slashes typically freshly typed in? Do you use the `<` magic?

Of course there's always the option of reparsing right before delete. Perhaps there could be an option saying "if the buffer is less than X characters long, reparse before delete; otherwise don't reparse."

**Comment by blaenk** [comment]
Yeah I'm using the default configuration besides this workaround. I guess at my normal typing speed it is often indeed the case that they're freshly typed in.

**Comment by felipeochoa** [comment]
Commit 79bedb1 should add this reparsing functionality natively, so once you've updated you shouldn't need your advice. Thanks for the report! I'm going to close this, but if the issue persists even after updating, feel free to reopen.
