### ISSUE TITLE
Incorrect handling of string context

### ISSUE THREAD

**Issue by Fuco1** [felipeochoa/rjsx-mode#57]
```js
export default () => (
    <div>
      You've created a user
    </div>
)
```

If you put the cursor before `You` and call `(syntax-ppss)` you will get `nil` for the string context, whereas placing the cursor at `created` and calling `(syntax-ppss)` will give you `39` (ascii for `'`).  This breaks some tools relying on the string/commend status as reported by emacs.  It would be cool if we could mark all the quotes in "text nodes" in the tree with text properties disabling the pairing of quotes.

See https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Properties.html#Syntax-Properties

Edit: You can even see the "error" in how github renders the snippet.  Quite convenient in regard to this report :D

**Comment by felipeochoa** [comment]
As of 4db1fc0, this problem is handled by setting the `syntax-table` text property of jsx text to `(standard-syntax-table)`. However, `syntax-ppss` won't pick up on that property if `parse-sexp-lookup-properties` is set to t. (I can reproduce this issue problem when setting it to nil, but otherwise I can't). 

If `parse-sexp-lookup-properties` is the problem here, maybe it's worth automatically setting the variable when `rjsx-mode` is enabled. I'd originally refrained from doing that, but can't quite remember why. It seems like an odd detail to have users of rjsx have to konw

**Comment by Fuco1** [comment]
Thanks, that works fine.  I've missed the commit since I'm using this fork https://github.com/antifuchs/rjsx-mode with flow support.

I'm planning on extracting the flow code into a separate package and making it a minor mode (I'm not sure why andreas started it as fork of this project as there are no dependencies).

I think it's worth it setting the variable by default, it doesn't really slow things much and as you say is something quite obscure and internal.

**Comment by felipeochoa** [comment]
Sorry to reopen this, but I want to make sure we identify the correct issue. `js2-mode` already sets `parse-sexp-lookup-properties` to `t`, and since `rjsx-mode` derives from `js2`, that should be automatically set. Would you mind checking if there's something in your config that would set it back to `nil`? Does simply adding `(setq parse-sexp-lookup-properties t)` to your rjsx hook solve the problem?

**Comment by Fuco1** [comment]
My problem was that I was running an old version of this package which did not set the syntax property. `js2-mode` sets `parse-sexp-lookup-properties` to `t` and everything behaves as expected.  I think there is no action required on your part.

From my POV this is solved and good to close.

**Comment by felipeochoa** [comment]
Great, thanks!
